name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: Hello
                required: true
                description: A cheerful word
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            GREET: ${{ inputs.greeting }} # 中間環境変数
        steps:
            - run: echo ${{ inputs.greeting }}